---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install and configure Vector
  hosts: vector_servers
  become: true
  roles:
    - vector-role

- name: Install and configure LightHouse
  hosts: lighthouse
  become: true
  roles:
    - lighthouse-role

